### ISSUE TITLE
Option to display tasks from a particular board

### ISSUE THREAD

**Issue by kbrock84** [klauscfhq/taskbook#74]
Current commands to display tasks:
<code>tb</code> or <code>tb --timeline</code>

With many boards and tasks these options can result in an overwhelmingly large list. We do have the option to find with <code>tb -f</code> but this only matches text in the task and not board names.

It would be nice to have an option to display tasks from a particular board like this:
<code>tb @some_board</code>

resulting in only tasks from that board:
![image](https://user-images.githubusercontent.com/31415142/43912722-ea8907ba-9bb7-11e8-8508-45370a3f1e56.png)

**Comment by JordanAdams** [comment]
Can’t you already do this with `$ tb -l @some_board`?

**Comment by kbrock84** [comment]
You're right! I was trying <code>tb -l @some_boad</code>. Guess I should read the docs a little closer.

**Comment by DLvalentine** [comment]
I feel like this could be a better interaction, though. Something like `tb @board` would be *really* nice, instead of passing a flag. I know there's an issue ( #72 ) to replace flags with commands. I think this change would be a good quality of life opportunity, as it feels more intuitive instead of using the `list` flag.
